name: pyenv test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: setup pyenv
        id: pyenv_installation
        uses: "gabrielfalcao/pyenv-action@v5"

      - name: pyenv versions
        run:
          pyenv versions
